name: Deploy to Google Cloud Run

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:

    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '422.0.0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'