name: Deploy to Google Cloud Run

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '422.0.0'

      - name: 'Deploy'
        run: >
          gcloud run deploy spring-cloud-config-server --source=. --concurrency=default --cpu=1 --cpu-throttling
          --min-instances=0 --max-instances=3 --memory=1Gi --platform=managed --port=8888 --timeout=300s
          --allow-unauthenticated --revision-suffix=${GITHUB_SHA::7} --region=europe-north1 --project=kotoant
